-- NIGHTMARE HOUSE 2 PORT TO GMOD
-- Den Urakolouy

include("nh2/soundscripts/announcer_soundfiles.lua")
include("nh2/soundscripts/captionsample.lua")
include("nh2/soundscripts/emily_soundfiles.lua")
include("nh2/soundscripts/game_sounds.lua")
include("nh2/soundscripts/game_sounds_ambient_generic.lua")
include("nh2/soundscripts/game_sounds_weapons.lua")
include("nh2/soundscripts/nh2sounds.lua")
include("nh2/soundscripts/npc_sounds_nh_guard.lua")
include("nh2/soundscripts/npc_sounds_nhdemon.lua")
include("nh2/soundscripts/npc_sounds_nhzombie.lua")
include("nh2/soundscripts/npc_sounds_stalker.lua")
include("nh2/soundscripts/romero_soundfiles.lua")
include("nh2/soundscripts/swat_soundfiles.lua")

AddCSLuaFile("nh2/soundscripts/announcer_soundfiles.lua")
AddCSLuaFile("nh2/soundscripts/captionsample.lua")
AddCSLuaFile("nh2/soundscripts/emily_soundfiles.lua")
AddCSLuaFile("nh2/soundscripts/game_sounds.lua")
AddCSLuaFile("nh2/soundscripts/game_sounds_ambient_generic.lua")
AddCSLuaFile("nh2/soundscripts/game_sounds_weapons.lua")
AddCSLuaFile("nh2/soundscripts/nh2sounds.lua")
AddCSLuaFile("nh2/soundscripts/npc_sounds_nh_guard.lua")
AddCSLuaFile("nh2/soundscripts/npc_sounds_nhdemon.lua")
AddCSLuaFile("nh2/soundscripts/npc_sounds_nhzombie.lua")
AddCSLuaFile("nh2/soundscripts/npc_sounds_stalker.lua")
AddCSLuaFile("nh2/soundscripts/romero_soundfiles.lua")
AddCSLuaFile("nh2/soundscripts/swat_soundfiles.lua")